export const initialValues = [
  {
    name: "",
    email: "",
    phoneNumber: "",
    github: "",
    linkedin: "",
    website: "",
    coverLetter: "",
    cv: "",
  },
  {
    title: "",
    summary: "",
    slug: "",
    seoTitle: "",
    seoDescription: "",
    coverImage: "",
    content: "",
    isPublished: false,
    categories: [],
    langCode: "en",
    tags: [],
    keywords: [],
  },

  {
    name: "",
    slug: "",
    langCode: "en",
  },
  {
    title: "",
    coverImage: "",
    description: "",
    links: [],
    services: [],
    techStacks: [],
    serviceProvidedAt: "",
    seoTitle: "",
    seoDescription: "",
  },
  {
    name: "",
    profileImage: "",
    profession: "",
    socialLinks: [],
    review: "",
    published: false,
  },
  {
    title: "",
    summary: "",
    content: "",
    seoTitle: "",
    seoDescription: "",
  },
  {
    role: "",
    slug: "",
    location: "",
    shortDescription: "",
    description: "",
    seoTitle: "",
    seoDescription: "",
  },
  {
    email: "",
    password: "",
  },
  {
    requestorName: "",
    requestorEmail: "",
    description: "",
  },
];
