export const initialValues = [
  {
    name: "",
    email: "",
    phoneNumber: "",
    github: "",
    linkedin: "",
    website: "",
    coverLetter: "",
    cv: "",
  },
  {
    title: "",
    summary: "",
    slug: "",
    seoTitle: "",
    seoDescription: "",
    coverImage: "",
    content: "",
    categories: [],
    langCode: "",
    tags: [],
    keywords: [],
  },
];
